WEBAAssignmentProject/Controllers/RoleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WEBAAssignmentProject.Models;
using Microsoft.AspNet.Identity.EntityFramework;

namespace WEBAAssignmentProject.Controllers
{
    public class RoleController : Controller
    {

        ApplicationDbContext context;

        public RoleController()
        {

            context = new ApplicationDbContext();
        }
        // GET: Role
        //[Authorize(Roles = "administrator")]
        public ActionResult Index()
        {
            var roleList = context.Roles.ToList();
            return View(roleList);
        }
        public ActionResult Create()
        {
            var role = new IdentityRole();
            return View(role);
        }//end of Create() action method
        [HttpPost]
        // [Authorize(Roles = "administrator")]
        public ActionResult Create(IdentityRole inRole)
        {
            context.Roles.Add(inRole);
            context.SaveChanges();
            //Tell the web browser to call the RoleController's Index() action method so that
            //the user can see a list of roles (including the newly created role.
            return RedirectToAction("Index");
        }
    }
}

WEBAAssignmentProject/Views/Role/Create.cshtml
@model Microsoft.AspNet.Identity.EntityFramework.IdentityRole
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

<style type="text/css">
    #tbrole, .c {
        border: double;
    }
</style>


@using (Html.BeginForm())
{
    <table id="tbrole">
        <tr>
            <td class="c">Enter Role Name To be Created:</td>
            <td class="c">
                @Html.EditorFor(m => m.Name)
            </td>
        </tr>
    </table>
    <input type="submit" value="Create Role" />
}

WEBAAssignmentProject/Views/Role/Index.cshtml
@model IEnumerable<Microsoft.AspNet.Identity.EntityFramework.IdentityRole>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Available Roles For Application</h2>

@Html.ActionLink("Create Role", "Create", "Role")

<style type="text/css">
    #tbrole, .c {
        border: double;
    }
</style>

<table id="tbrole">
    <tr>
        <td class="c">
            Role Name
        </td>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td class="c">
                @item.Name
            </td>
        </tr>
    }
</table>